get_gh_ref_data: improve logic, increase ttl for commit query cache

diff --git a/etc/init.d/qosmate b/etc/init.d/qosmate
--- a/etc/init.d/qosmate
+++ b/etc/init.d/qosmate
@@ -308,53 +308,62 @@ get_gh_ref_data() {
 
 	gh_id="${component}_${version}"
 
-	# if previously stored data exists, use it without API call
 	eval "prev_ref=\"\${${gh_id}_ref}\"
 		prev_ver_type=\"\${${gh_id}_ver_type}\"
 		prev_upd_channel=\"\${${gh_id}_upd_channel}\""
+
+	# if previously stored data exists, use it without API query or cache check
 	if [ -n "$prev_ref" ] && [ -n "$prev_ver_type" ] && [ "$prev_upd_channel" = "$gh_channel" ]; then
-		eval "$4"='$prev_ref' "$5"='${gh_url_api}/tarball/${prev_ref}' "$6"='$prev_ver_type'
+		gh_ref="$prev_ref" gh_ver_type="$prev_ver_type"
+	else
+		# if commit hash is specified and it's 40-char long, use it directly without API query or cache check
+		case "$gh_channel" in
+			snapshot|branch=*|commit=*) [ "${#version}" = 40 ] && gh_ref="$version"
+		esac
+
+		if [ -z "$gh_ref" ]; then
+			# ref cache
+			local cache_file cache_filename="${gh_id}_${gh_channel}" ref_cache_dir="/tmp/qosmate_cache" cache_ttl
+			case "$gh_channel" in
+				commit=*) cache_ttl=2880 ;; # 48 hours
+				*) chache_ttl=10 # 10 minutes
+			esac
+			try_mkdir -p "$ref_cache_dir" || return 1
+
+			# clean up old cache
+			find "${ref_cache_dir:-?}" -maxdepth 1 -type f -mmin +"${cache_ttl}" -exec rm -f {} \; 2>/dev/null
+
+			# check if the query is cached
+			cache_file="$(find "${ref_cache_dir:-?}" -maxdepth 1 -type f -name "${cache_filename}" -print 2>/dev/null)"
+			case "$cache_file" in
+				'') ;; # found nothing
+				*[^"$_NL_"]*"${_NL_}"*[^"${_NL_}"]*)
+					# found multiple files - delete them
+					local file IFS="$_NL_"
+					for file in $cache_file; do
+						[ -n "$file" ] || continue
+						rm -f "$file"
+					done
+					IFS="$DEFAULT_IFS" ;;
+				*)
+					# found cached query
+					if [ -z "$IGNORE_CACHE" ] && [ -f "$cache_file" ] && read -r prev_ref prev_ver_type < "$cache_file" &&
+						[ -n "$prev_ref" ] && [ -n "$prev_ver_type" ]; then
+							gh_ref="$prev_ref" gh_ver_type="$prev_ver_type"
+					else
+						rm -f "${cache_file:-???}"
+					fi
+			esac
+		fi
+	fi
+
+	if [ -n "$gh_ref" ]; then
+		eval "$4"='$gh_ref' "$5"='${gh_url_api}/tarball/${gh_ref}' "$6"='$gh_ver_type'
 		return 0
 	fi
 
-	# ref cache
-	local cache_file cache_filename="${gh_id}_${gh_channel}" ref_cache_dir="/tmp/qosmate_cache" cache_ttl=10
-	try_mkdir -p "$ref_cache_dir" || return 1
-
-	# clean up old cache
-	find "${ref_cache_dir:-?}" -maxdepth 1 -type f -mmin +"${cache_ttl}" -exec rm -f {} \; 2>/dev/null
-
-	# check if the query is cached
-	cache_file="$(find "${ref_cache_dir:-?}" -maxdepth 1 -type f -name "${cache_filename}" -print 2>/dev/null)"
-	case "$cache_file" in
-		'') ;; # found nothing
-		*[^"$_NL_"]*"${_NL_}"*[^"${_NL_}"]*)
-			# found multiple files - delete them
-			local file IFS="$_NL_"
-			for file in $cache_file; do
-				[ -n "$file" ] || continue
-				rm -f "$file"
-			done
-			IFS="$DEFAULT_IFS" ;;
-		*)
-			# found cached query
-			if [ -z "$IGNORE_CACHE" ] && [ -f "$cache_file" ] && read -r prev_ref prev_ver_type < "$cache_file" &&
-				[ -n "$prev_ref" ] && [ -n "$prev_ver_type" ]; then
-					eval "$4"='$prev_ref' "$5"='${gh_url_api}/tarball/${prev_ref}' "$6"='$prev_ver_type'
-					return 0
-			else
-				rm -f "${cache_file:-???}"
-			fi
-	esac
-
 	try_mkdir -p "$ref_fetch_tmp_dir" || return 1
 	rm -f "$ref_ucl_err_file"
-
-	# if version is specified and it's 40-char long, use it directly without API query
-	case "$gh_channel" in
-		snapshot|branch=*|commit=*)
-			[ "${#version}" = 40 ] && gh_ref="$version"
-	esac
 
 	eval "main_branch=\"\${MAIN_BRANCH_${component}}\""
 	case "$gh_channel" in
